activated: true

messages:
  no-permission: " &f[&cОшибка&f]&c У вас недостаточно прав"
  enabled: " &f[&aУспех&f]&a Режим изменения шансов включен"
  disabled: " &f[&aУспех&f]&a Режим изменения шансов выключен"